/*******************************************************************************
 * Created by: shlomo hassid.
 * Release Version : 1.0
 * Creation Date: 10/12/2014
 * Author E-mail: Shlomohassid@gmail.com
 * Suppot: support@14tec.com
 * require: jQuery latest, jQuery easing, hotspot.1.0.css	
 * Copyright 2014, shlomo hassid.
*******************************************************************************/

(function(d){d.hotspot=function(e,h){var g={debug:!1,margin:{t:5,l:5,b:5,r:5},pagePos:"nw",radius:0,mainSize:50,open:"hor",easing:"swing",delayBetween:200,animDuration:800,smoothTransition:!0,addShadow:!1,elements:[],customClass:!1,closeOutClick:!0,openCallback:function(){},closeCallback:function(){},beforeOpen:function(){},beforeClose:function(){},created:function(){},def_pad:20,def_bg:"black",def_sizeReduce:"15%",def_cursor_disable:"default",def_close_disable:!0,def_open_enable:!1,def_newTab:!0,
main_wider:2,def_iconPre:"hsi_",def_iconSuf:"_d"},a=this;a.settings={};var f=d(e),k=null,u=d("<div />").append(d(e).clone()).html();h=h||{};a.init=function(){a.settings=d.extend({},g,h);var b=a.timerSet=null;"div"!==f.eq(0).get(0).tagName.toLowerCase()&&(b=f.clone(),oldAttr=f.prop("attributes"),main_new=d("<div />"),d.each(oldAttr,function(){0!==this.name.indexOf("h-")&&d(main_new).attr(this.name,this.value)}),f.replaceWith(d(main_new)),f=d(main_new),e=d(main_new)[0],u=d("<div />").append(d(main_new).clone()).html(),
oldAttr=main_new=null);a.main_ele=f;a.originalHTML=u;var c=f.parent(),v=d(c).get(0).tagName,s={},l={};a.unique_namespace=a.methods.uniqueId(10);a._shadowToAdd=!1;a.ele_arr=[];if(null!==b){"undefined"!==typeof b.attr("H-margin")&&(results=a.methods.margin_parse(b.attr("H-margin")))&&(a.settings.margin=results);"undefined"!==typeof b.attr("H-mainSize")&&(results=a.methods.int_parse(b.attr("H-mainSize")))&&(a.settings.mainSize=results);"undefined"!==typeof b.attr("H-pagePos")&&(results=a.methods.valid_pos(b.attr("H-pagePos")))&&
(a.settings.pagePos=results);"undefined"!==typeof b.attr("H-radius")&&(results=a.methods.radius_parse(b.attr("H-radius")))&&(a.settings.radius=results);"undefined"!==typeof b.attr("H-open")&&(results=a.methods.valid_open(b.attr("H-open")))&&(a.settings.open=results);"undefined"!==typeof b.attr("H-easing")&&(results=a.methods.valid_easing(b.attr("H-easing")))&&(a.settings.easing=results);"undefined"!==typeof b.attr("H-delayBetween")&&(results=a.methods.int_parse(b.attr("H-delayBetween")))&&(a.settings.delayBetween=
results);"undefined"!==typeof b.attr("H-animDuration")&&(results=a.methods.int_parse(b.attr("H-animDuration")))&&(a.settings.animDuration=results);"undefined"!==typeof b.attr("H-smoothTransition")&&(results=a.methods.valid_bool(b.attr("H-smoothTransition")),"x"!==results&&(a.settings.smoothTransition=results));"undefined"!==typeof b.attr("H-addShadow")&&(results=a.methods.valid_pos(b.attr("H-addShadow")),"x"!==results&&(a.settings.addShadow=results));"undefined"!==typeof b.attr("H-customClass")&&
b.attr("H-customClass").trim().length&&(a.settings.customClass=b.attr("H-customClass").trim());if(b.find("li").length)for(a.settings.elements=[],$main_inline=b.find("li").eq(0),a.settings.elements[0]={title:"undefined"!==typeof $main_inline.attr("H-title")?$main_inline.attr("H-title"):"",bg:"undefined"!==typeof $main_inline.attr("H-bg")?$main_inline.attr("H-bg"):a.settings.def_bg,hoverBg:"undefined"!==typeof $main_inline.attr("H-hoverBg")?$main_inline.attr("H-hoverBg"):!1,icon:"string"===typeof $main_inline.attr("H-icon")?
$main_inline.attr("H-icon"):!1,sizeReduce:"undefined"!==typeof $main_inline.attr("H-sizeReduce")?$main_inline.attr("H-sizeReduce"):a.settings.def_sizeReduce},l=1;l<b.find("li").length;l++)$sub_inline=b.find("li").eq(l),a.settings.elements[l]={title:"undefined"!==typeof $sub_inline.attr("H-title")?$sub_inline.attr("H-title"):"",bg:"undefined"!==typeof $sub_inline.attr("H-bg")?$sub_inline.attr("H-bg"):a.settings.elements[0].bg,hoverBg:"undefined"!==typeof $sub_inline.attr("H-hoverBg")?$sub_inline.attr("H-hoverBg"):
!1,pad:"undefined"!==typeof $sub_inline.attr("H-pad")?$sub_inline.attr("H-pad"):a.settings.def_pad,icon:"string"===typeof $sub_inline.attr("H-icon")?$sub_inline.attr("H-icon"):!1,sizeReduce:"undefined"!==typeof $sub_inline.attr("H-sizeReduce")?$sub_inline.attr("H-sizeReduce"):a.settings.elements[0].sizeReduce,href:"undefined"!==typeof $sub_inline.attr("H-href")?$sub_inline.attr("H-href"):!1,func:"undefined"!==typeof $sub_inline.attr("H-func")?$sub_inline.attr("H-func"):!1,newTab:"undefined"!==typeof $sub_inline.attr("H-newTab")?
$sub_inline.attr("H-newTab"):!0},$sub_inline=null;$main_inline=$sub_inline=b=null}a.methods.validate_options();if(void 0!==typeof a.settings.elements[0]){b=a.methods.validate_main(a.settings.elements[0]);a.settings.mainIcon=b.icon;a.settings.mainTitle=b.title;a.settings.mainSizeReduce=b.sizeReduce;a.settings.mainBg=b.bg;a.settings.mainHoverBg=b.hoverBg;b=null;f.addClass("main_hotspot");a.settings.smoothTransition&&f.addClass("smooth_transition_hotspot");switch(a.settings.addShadow){case "ne":f.addClass("shadow_ne_hotspot");
a._shadowToAdd="shadow_ne_hotspot";break;case "nw":f.addClass("shadow_nw_hotspot");a._shadowToAdd="shadow_nw_hotspot";break;case "se":f.addClass("shadow_se_hotspot");a._shadowToAdd="shadow_se_hotspot";break;case "sw":f.addClass("shadow_sw_hotspot"),a._shadowToAdd="shadow_sw_hotspot"}a.settings.mainIcon&&f.addClass(a.settings.def_iconPre+a.settings.mainIcon);f.addClass(a.unique_namespace);a.settings.customClass&&f.addClass(a.settings.customClass);""!==a.settings.mainTitle&&f.attr("title",a.settings.mainTitle);
a.settings.mainHoverBg&&(f.data("bgcolor-in",a.settings.mainHoverBg),f.bind("mouseenter."+a.unique_namespace,a.methods.hoverInBg),f.bind("mouseleave."+a.unique_namespace,a.methods.hoverOutBg));f.css({position:"absolute",width:a.settings.mainSize+a.settings.main_wider,height:a.settings.mainSize+a.settings.main_wider,backgroundColor:a.settings.mainBg,"z-index":a.settings.elements.length+1,borderTopLeftRadius:a.settings.radius.tl,borderTopRightRadius:a.settings.radius.tr,borderBottomLeftRadius:a.settings.radius.bl,
borderBottomRightRadius:a.settings.radius.br,WebkitBorderTopLeftRadius:a.settings.radius.tl,WebkitBorderTopRightRadius:a.settings.radius.tr,WebkitBorderBottomLeftRadius:a.settings.radius.bl,WebkitBorderBottomRightRadius:a.settings.radius.br,MozBorderTopLeftRadius:a.settings.radius.tl,MozBorderTopRightRadius:a.settings.radius.tr,MozBorderBottomLeftRadius:a.settings.radius.bl,MozBorderBottomRightRadius:a.settings.radius.br,backgroundSize:a.settings.mainSizeReduce});f.wrap("<div />");k=f.parent().addClass("wraper_hotspot reset_hotspot");
"body"===v.toLowerCase()?k.css({position:"fixed","z-index":1100,width:a.settings.mainSize+a.settings.main_wider,height:a.settings.mainSize+a.settings.main_wider}):(d(c).css({position:"relative"}),k.css({position:"absolute","z-index":1E3,width:a.settings.mainSize+a.settings.main_wider,height:a.settings.mainSize+a.settings.main_wider}));switch(a.settings.pagePos.toLowerCase()){case "ne":k.css({top:a.settings.margin.t,right:a.settings.margin.r});s={top:0,right:0};l={top:-1,right:-1};break;case "se":k.css({bottom:a.settings.margin.b,
right:a.settings.margin.r});s={bottom:0,right:0};l={bottom:-1,right:-1};break;case "sw":k.css({bottom:a.settings.margin.b,left:a.settings.margin.l});s={bottom:0,left:0};l={bottom:-1,left:-1};break;default:k.css({top:a.settings.margin.t,left:a.settings.margin.l}),s={top:0,left:0},l={top:-1,left:-1}}f.css(l);f.attr("stat","close");f.attr("stat-dis","enable");l=v=c=null;d.each(a.settings.elements,function(b,c){if(0!==b){c=a.methods.validate_ele(c);var e=d("<div title='"+c.title+"' pad='"+c.pad+"' />").css({position:f.css("position"),
backgroundColor:c.bg,width:a.settings.mainSize,height:a.settings.mainSize,"z-index":a.settings.elements.length-b,borderTopLeftRadius:a.settings.radius.tl,borderTopRightRadius:a.settings.radius.tr,borderBottomLeftRadius:a.settings.radius.bl,borderBottomRightRadius:a.settings.radius.br,WebkitBorderTopLeftRadius:a.settings.radius.tl,WebkitBorderTopRightRadius:a.settings.radius.tr,WebkitBorderBottomLeftRadius:a.settings.radius.bl,WebkitBorderBottomRightRadius:a.settings.radius.br,MozBorderTopLeftRadius:a.settings.radius.tl,
MozBorderTopRightRadius:a.settings.radius.tr,MozBorderBottomLeftRadius:a.settings.radius.bl,MozBorderBottomRightRadius:a.settings.radius.br,backgroundSize:c.sizeReduce}).css(s).addClass("ele_hotspot");c.hoverBg&&(d(e).data("bgcolor-in",c.hoverBg),d(e).bind("mouseenter."+a.unique_namespace,a.methods.hoverInBg),d(e).bind("mouseleave."+a.unique_namespace,a.methods.hoverOutBg));a.settings.smoothTransition&&d(e).addClass("smooth_transition_hotspot");d(e).addClass(a.unique_namespace);c.icon&&d(e).addClass(a.settings.def_iconPre+
c.icon);a.settings.customClass&&d(e).addClass(a.settings.customClass);k.append(e);a.ele_arr.push(e);a.methods.ele_behavior(e,c)}});f.bind("click."+a.unique_namespace,function(){"disable"!==d(this).attr("stat-dis")&&("open"===d(this).attr("stat")?a.close(!0,!0):a.open(!0,!0))});a.settings.closeOutClick&&d(document).bind("click."+a.unique_namespace,function(b){d(b.target).is("."+a.unique_namespace)||"disable"!==f.attr("stat-dis")&&"close"!==f.attr("stat")&&a.close(!0)});a.settings.debug&&console.log("Hotspot created. unique:"+
a.unique_namespace+" id: "+f.attr("id"));a.settings.created.call(e)}else a.settings.debug&&console.log("Main ele not set.")};a.destroy=function(){var b=d(a.originalHTML);k.find("div").each(function(){d(this).unbind("."+a.unique_namespace)});d(document).unbind("."+a.unique_namespace);k.replaceWith(b);a.methods.clear_timer();a.settings.debug&&console.log("Hotspot destroyed.   unique:"+a.unique_namespace);return b};a.rebuild=function(b){var c=a.destroy();b=new d.hotspot(c,b);d(c).data("hotspot",b);b.settings.debug&&
console.log("Hotspot rebuilt.   unique:"+b.unique_namespace)};a.disable=function(b,c){f.attr("stat-dis","disable");b&&f.css({cursor:b});c&&a.close(!0,!0);a.settings.debug&&console.log("Hotspot disabled.  unique:"+a.unique_namespace)};a.enable=function(b){var c=f.attr("stat-dis");f.attr("stat-dis","enable");"disable"===c&&(f.css({cursor:""}),b&&a.open(!0,!0));a.settings.debug&&console.log("Hotspot enabled.  unique:"+a.unique_namespace)};a.open=function(b,c){b&&a.methods.hook_beforeOpen();"close"===
f.attr("stat")&&(f.attr("stat","open"),a.methods.expand_bar(a.ele_arr,"open",a._shadowToAdd,c))};a.close=function(b,c){b&&a.methods.hook_beforeClose();"open"===f.attr("stat")&&(f.attr("stat","close"),a.methods.expand_bar(a.ele_arr,"close",a._shadowToAdd,c))};a.methods={validate_options:function(){"object"!==typeof a.settings.margin&&("string"===typeof a.settings.margin||"number"===typeof a.settings.margin?(results=a.methods.margin_parse(a.settings.margin))?a.settings.margin=results:(a.settings.margin=
g.margin,a.settings.debug&&console.log("Bad variable set for 'margin' should be object : { t:numer, b:number, l:number, r:number }")):(a.settings.margin=g.margin,a.settings.debug&&console.log("Bad variable set for 'margin' should be object : { t:numer, b:number, l:number, r:number }")));"number"!==typeof a.settings.mainSize&&((results=a.methods.int_parse(a.settings.mainSize))?a.settings.mainSize=results:(a.settings.mainSize=g.mainSize,a.settings.debug&&console.log("Bad variable set for 'mainSize' should be number >= 0")));
"string"===typeof a.settings.pagePos?(results=a.methods.valid_pos(a.settings.pagePos))?a.settings.pagePos=results:(a.settings.mainSize=g.pagePos,a.settings.debug&&console.log("Bad variable set for 'pagePos' should be string : se|sw|ne|nw")):(a.settings.mainSize=g.pagePos,a.settings.debug&&console.log("Bad variable set for 'pagePos' should be string : se|sw|ne|nw"));"object"!==typeof a.settings.radius&&("string"===typeof a.settings.radius||"number"===typeof a.settings.radius?(results=a.methods.radius_parse(a.settings.radius))?
a.settings.radius=results:(a.settings.radius=g.radius,a.settings.debug&&console.log("Bad variable set for 'radius' should be number >= 0 : se|sw|ne|nw")):(a.settings.radius=g.radius,a.settings.debug&&console.log("Bad variable set for 'radius' should be number >= 0 : se|sw|ne|nw")));"string"===typeof a.settings.open?(results=a.methods.valid_open(a.settings.open))?a.settings.open=results:(a.settings.open=g.open,a.settings.debug&&console.log("Bad variable set for 'open' should be be string : hor|ver")):
(a.settings.open=g.open,a.settings.debug&&console.log("Bad variable set for 'open' should be be string : hor|ver"));"string"===typeof a.settings.easing?(results=a.methods.valid_easing(a.settings.easing))?a.settings.easing=results:(a.settings.easing=g.easing,a.settings.debug&&console.log("Bad variable set for 'easing' should be be string : go to ducumentation for more details")):(a.settings.easing=g.easing,a.settings.debug&&console.log("Bad variable set for 'easing' should be be string : go to ducumentation for more details"));
"number"!==typeof a.settings.delayBetween&&((results=a.methods.int_parse(a.settings.delayBetween))?a.settings.delayBetween=results:(a.settings.delayBetween=g.delayBetween,a.settings.debug&&console.log("Bad variable set for 'delayBetween' should be be number >= 0")));"number"!==typeof a.settings.animDuration&&((results=a.methods.int_parse(a.settings.animDuration))?a.settings.animDuration=results:(a.settings.animDuration=g.animDuration,a.settings.debug&&console.log("Bad variable set for 'animDuration' should be be number >= 0")));
"boolean"!==typeof a.settings.smoothTransition&&(results=a.methods.valid_bool(a.settings.smoothTransition),"x"!==results?a.settings.smoothTransition=results:(a.settings.smoothTransition=g.smoothTransition,a.settings.debug&&console.log("Bad variable set for 'smoothTransition' should be be boolean|string: true|false")));"string"===typeof a.settings.addShadow?(results=a.methods.valid_pos(a.settings.addShadow),results||(a.settings.addShadow=g.addShadow,a.settings.debug&&console.log("Bad variable set for 'addShadow' should be be boolean|string: true|false"))):
!1!==a.settings.addShadow&&0!==a.settings.addShadow&&(a.settings.addShadow=g.addShadow,a.settings.debug&&console.log("Bad variable set for 'addShadow' should be be boolean|string: true|false"));"string"===typeof a.settings.customClass?2>a.settings.customClass.trim().length&&(a.settings.customClass=g.customClass,a.settings.debug&&console.log("Bad variable set for 'customClass' should be be string > 2chars")):!1!==a.settings.customClass&&0!==a.settings.customClass&&(a.settings.customClass=g.customClass,
a.settings.debug&&console.log("Bad variable set for 'customClass' should be be string > 2chars"));"function"!==typeof a.settings.openCallback&&(a.settings.openCallback=g.openCallback,a.settings.debug&&console.log("Bad setting for `openCallback` should be a Function."));"function"!==typeof a.settings.closeCallback&&(a.settings.closeCallback=g.closeCallback,a.settings.debug&&console.log("Bad setting for `closeCallback` should be a Function."));"function"!==typeof a.settings.beforeOpen&&(a.settings.beforeOpen=
g.beforeOpen,a.settings.debug&&console.log("Bad setting for `beforeOpen` should be a Function."));"function"!==typeof a.settings.beforeClose&&(a.settings.beforeClose=g.beforeClose,a.settings.debug&&console.log("Bad setting for `beforeClose` should be a Function."));"function"!==typeof a.settings.created&&(a.settings.created=g.created,a.settings.debug&&console.log("Bad setting for `created` should be a Function."));"boolean"!==typeof a.settings.closeOutClick&&(results=a.methods.valid_bool(a.settings.closeOutClick),
"x"!==results?a.settings.closeOutClick=results:(a.settings.closeOutClick=g.closeOutClick,a.settings.debug&&console.log("Bad variable set for 'closeOutClick' should be be boolean|string: true|false")))},validate_main:function(b){if("undefined"===typeof b.title||""===b.title)b.title="";if("undefined"===typeof b.bg||""===b.bg)b.bg=a.settings.def_bg;if("undefined"===typeof b.hoverBg||""===b.hoverBg)b.hoverBg=!1;b.icon="string"!==typeof b.icon||""===b.icon?!1:a.methods.valid_icon(b.icon);"undefined"===
typeof b.sizeReduce||""===b.sizeReduce||"false"===b.sizeReduce||!1===b.sizeReduce?(b.sizeReduce=a.settings.def_sizeReduce,b.sizeReduce=a.methods.sizeReduce_parse(b.sizeReduce)):(b.sizeReduce=a.methods.sizeReduce_parse(b.sizeReduce),b.sizeReduce||(b.sizeReduce=a.settings.def_sizeReduce,b.sizeReduce=a.methods.sizeReduce_parse(b.sizeReduce)));return b},validate_ele:function(b){if("undefined"===typeof b.title||""===b.title||"false"===b.title)b.title="";if("undefined"===typeof b.bg||""===b.bg)b.bg=a.settings.mainBg;
if("undefined"===typeof b.hoverBg||""===b.hoverBg)b.hoverBg=!1;if("undefined"===typeof b.pad||""===b.pad)b.pad=a.settings.def_pad;b.icon="string"!==typeof b.icon||""===b.icon?!1:a.methods.valid_icon(b.icon);"undefined"===typeof b.sizeReduce||""===b.sizeReduce||"false"===b.sizeReduce||!1===b.sizeReduce?b.sizeReduce=a.settings.mainSizeReduce:(b.sizeReduce=a.methods.sizeReduce_parse(b.sizeReduce),b.sizeReduce||(b.sizeReduce=a.settings.mainSizeReduce));if("undefined"===typeof b.href||""===b.href)b.href=
!1;if("undefined"===typeof b.func||""===b.func)b.func=!1;if("undefined"===typeof b.newTab||""===b.newTab)b.newTab=a.settings.def_newTab;return b},expand_bar:function(b,c,e,f){var g=a.settings.pagePos.toLowerCase(),h=a.settings.open,k=a.settings.mainSize,n=a.settings.easing,p=a.settings.animDuration,q=a.settings.delayBetween,r=0;e||(e="");"open"===c?d.each(b,function(c,t){r+=parseInt(d(t).attr("pad"));var m=null;c+1===b.length&&f&&(m=a.methods.hook_openCallBack);switch(g+h){case "nwver":case "never":d(t).stop().animate({top:k*
(c+1)+r},p+q*c,n,m).addClass(e);break;case "nwhor":case "swhor":d(t).stop().animate({left:k*(c+1)+r},p+q*c,n,m).addClass(e);break;case "nehor":case "sehor":d(t).stop().animate({right:k*(c+1)+r},p+q*c,n,m).addClass(e);break;case "swver":case "sever":d(t).stop().animate({bottom:k*(c+1)+r},p+q*c,n,m).addClass(e)}}):d.each(b,function(c,k){var m=null;c+1===b.length&&f&&(m=a.methods.hook_closeCallBack);switch(g+h){case "nwver":case "never":d(k).stop().animate({top:0},p+q*c,n,m).removeClass(e);break;case "nwhor":case "swhor":d(k).stop().animate({left:0},
p+q*c,n,m).removeClass(e);break;case "nehor":case "sehor":d(k).stop().animate({right:0},p+q*c,n,m).removeClass(e);break;case "swver":case "sever":d(k).stop().animate({bottom:0},p+q*c,n,m).removeClass(e)}})},ele_behavior:function(b,c){var e="_blank";c.newTab||(e="_self");c.href&&c.func&&d(b).bind("click."+a.unique_namespace,function(){window.open(c.href,e);"string"===typeof c.func&&eval(c.func);"function"===typeof c.func&&c.func.call(b)});c.href&&!c.func&&d(b).bind("click."+a.unique_namespace,function(){window.open(c.href,
e)});!c.href&&c.func&&d(b).bind("click."+a.unique_namespace,function(){"string"===typeof c.func&&eval(c.func);"function"===typeof c.func&&c.func.call(b)})},uniqueId:function(a){var c="_0123456789ABCDEFGHIJKLMNOPQRSTUVWXTZabcdefghiklmnopqrstuvwxyz".split("");a||(a=10);for(var d="",e=0;e<a;e++)d+=c[Math.floor(Math.random()*c.length)];return d},margin_parse:function(b){"number"===typeof b&&(b=b.toString());if(b.match("^{")&&b.match("}$"))try{return eval("("+b+")")}catch(c){return a.settings.debug&&(c instanceof
SyntaxError?console.log("Bad object set for 'margin'.  Syntax error - "+c.message):console.log("Bad object set for 'margin'.  "+c.message)),!1}_value=b.trim().split(" ");_return=!1;if(1===_value.length||2===_value.length||4===_value.length){for(b=0;b<_value.length;b++)_value[b]=_value[b].replace(/\D/g,"");for(b=0;b<_value.length;b++)_value[b]=isNaN(Number(_value[b]))?g.margin.t:Number(_value[b]);switch(_value.length){case 1:_return={t:_value[0],l:_value[0],b:_value[0],r:_value[0]};break;case 2:_return=
{t:_value[0],l:_value[1],b:_value[0],r:_value[1]};break;default:_return={t:_value[0],l:_value[3],b:_value[2],r:_value[1]}}}return _return},sizeReduce_parse:function(b){if("number"===typeof b)return b=a.settings.mainSize-b,b=b.toString()+"px",b+" "+b;if("string"===typeof b){b=b.trim().split(" ");for(var c=0;2>c;c++)if("undefined"!==typeof b[c])if(b[c]=b[c].replace(/[^0-9%]/g,""),/%/i.test(b[c]))if(b[c]=parseInt(b[c].replace(/%/g,"")),isNaN(b[c]))if(1===c)b[c]=b[c-1];else return!1;else b[c]=a.settings.mainSize-
Math.floor(b[c]/100*a.settings.mainSize);else if(b[c]=parseInt(b[c]),isNaN(b[c]))if(1===c)b[c]=b[c-1];else return!1;else b[c]=a.settings.mainSize-b[c];else if(1===c)b.push(b[c-1]);else return!1;return b.join("px ")+"px"}return!1},radius_parse:function(b){"number"===typeof b&&(b=b.toString());if(b.match("^{")&&b.match("}$"))try{return eval("("+b+")")}catch(c){return a.settings.debug&&(c instanceof SyntaxError?console.log("Bad object set for 'radius'.  Syntax error:"+c.message):console.log("Bad object set for 'radius'.  "+
c.message)),!1}_value=b.trim().split(" ");_return=!1;if(1===_value.length||4===_value.length){for(b=0;b<_value.length;b++)_value[b]=_value[b].replace(/\D/g,"");for(b=0;b<_value.length;b++)_value[b]=isNaN(Number(_value[b]))?g.radius:Number(_value[b]);switch(_value.length){case 1:_return={tl:_value[0],tr:_value[0],br:_value[0],bl:_value[0]};break;default:_return={tl:_value[0],tr:_value[3],br:_value[2],bl:_value[1]}}}return _return},int_parse:function(a){_value=a.trim().replace(/\D/g,"");return isNaN(Number(_value))?
!1:Number(_value)},valid_pos:function(a){_value=a.trim();switch(_value){case "sw":case "se":case "ne":case "nw":return _value;default:return!1}},valid_open:function(a){_value=a.trim();switch(_value){case "ver":case "hor":return _value;default:return!1}},valid_easing:function(a){_value=a.trim().replace(/[\W_]+/g,"");return _value.length?_value:!1},valid_bool:function(a){_value="string"===typeof a?a.trim():a;switch(_value){case "true":case 1:case "1":return!0;case "false":case 0:case "0":return!1;default:return"x"}},
valid_icon:function(b){b=b.replace(new RegExp("^"+a.settings.def_iconPre,"i"),"");/(_d|_w)$/.test(b)||(b+=a.settings.def_iconSuf);return b},hoverInBg:function(){d(this).data("bgcolor-out",d(this).css("background-color")).css("background-color",d(this).data("bgcolor-in"))},hoverOutBg:function(){d(this).css("background-color",d(this).data("bgcolor-out"))},clear_timer:function(){a.settings.debug&&console.log("cleard");clearInterval(a.timerSet)},set_delay:function(){a.timerSet=setInterval(function(){},
a.settings.delayHover)},hook_closeCallBack:function(){a.settings.closeCallback.call(e)},hook_openCallBack:function(){a.settings.openCallback.call(e)},hook_beforeClose:function(){a.settings.beforeClose.call(e)},hook_beforeOpen:function(){a.settings.beforeOpen.call(e)}};a.init();return a};d.fn.destroy_hotspot=function(){return this.each(function(){d(this).data("hotspot").destroy()})};d.fn.rebuild_hotspot=function(e){e=e||d(this).data("hotspot").settings;e=d.extend({},d(this).data("hotspot").settings,
e);return this.each(function(){d(this).data("hotspot").rebuild(e)})};d.fn.enable_hotspot=function(e){e=!1===e||!0===e?e:d(this).data("hotspot").settings.def_open_enable;return this.each(function(){d(this).data("hotspot").enable(e)})};d.fn.disable_hotspot=function(e,h){e=e||d(this).data("hotspot").settings.def_cursor_disable;h=!1===h||!0===h?h:d(this).data("hotspot").settings.def_close_disable;return this.each(function(){d(this).data("hotspot").disable(e,h)})};d.fn.open_hotspot=function(e,h){e=!1===
e||!0===e?e:!1;h=!1===h||!0===h?h:!1;return this.each(function(){d(this).data("hotspot").open(e,h)})};d.fn.close_hotspot=function(e,h){e=!1===e||!0===e?e:!1;h=!1===h||!0===h?h:!1;return this.each(function(){d(this).data("hotspot").close(e,h)})};d.fn.hotspot=function(e){return this.each(function(){if(void 0===d(this).data("hotspot")){var h=new d.hotspot(this,e);"undefined"!==typeof h.main_ele&&d(h.main_ele).data("hotspot",h)}})}})(jQuery);